# Generated by Django 4.0.3 on 2022-04-09 15:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_registration_options_registration_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.AlterField(
            model_name='registration',
            name='cam_photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gsp_location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='height',
            field=models.FloatField(),
        ),
    ]
