# Generated by Django 4.0.3 on 2022-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], default='select gender', max_length=10),
        ),
    ]
